version: "2.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./controllers.js:/var/www/html/controllers.js
      - ./guestbook.php:/var/www/html/guestbook.php
      - ./index.php:/var/www/html/index.php
      # - ./fancy.js:/var/www/html/fancy.js
    depends_on:
      - redis
    environment:
      GET_HOSTS_FROM: env
      REDIS_MASTER_SERVICE_HOST: redis
      REDIS_SLAVE_SERVICE_HOST: redis
    ports:
      - "9000:80"

  redis:
    image: redis
